### ISSUE TITLE
Questions about the experimental results in the paper.

### ISSUE THREAD

**Issue by Leekh951** [yutongwangBIT/GOReloc#5]
Thank you for your excellent paper.  I would like to ask if it would be possible to share the object ground truth (GT) data used in your study, as it would be valuable for my work.

Thank you for your time, and I look forward to your response.

**Comment by yutongwangBIT** [comment]
Hi, what do you mean by "object ground truth"?

**Comment by Leekh951** [comment]
![table1](https://github.com/user-attachments/assets/9d5f0293-b246-4740-bcce-91d6584b0dfe)
I apologize if my previous message caused any confusion.
Regarding the results in the attached Table 1, I would like to cite your work. I understood that for the center distance and IoU metrics, you projected the associated objects onto the image based on the ground truth pose and compared them with the matched detection bounding boxes. However, I am curious which metric you used for **accuracy** in the MOT evaluation.
Did you use MOTA?

**Comment by yutongwangBIT** [comment]
yes, it is MOTA

**Comment by Leekh951** [comment]
Thank you! Have a great day!
