### ISSUE TITLE
What's the version of protoc in your project?

### ISSUE THREAD

**Issue by zcj808** [yutongwangBIT/GOReloc#6]

**Comment by zcj808** [comment]
The version is 5.28.1 written on top of file `osmap.pb.cc`. And I suffer lots of troubles from configuration of protoc and there is an efficient solution [https://blog.csdn.net/ffffanfantastic/article/details/131570880](url). Also, I suggest it will be better that the author cite OA-SLAM and ORB-SLAM2 in the acknowledge of the readme.

**Comment by yutongwangBIT** [comment]
good suggestion.
