### ISSUE TITLE
Warning failed to open file: /home/yutong/OA-SLAM/Data/diamond_all/keyframes_poses_diamond_all.json

### ISSUE THREAD

**Issue by YuLong73** [yutongwangBIT/GOReloc#7]
In line 147 of the two files loc_tum.cc and loc_diamond.cc, the absolute path {std::string filename_json ="/home/yutong/OASLAM/Data/diamond_all/keyframes_poses_diamond_all.json";} is used to read the json file. I downloaded OA-SLAM, but did not find diamond_all/keyframes_poses_diamond_all.json

**Comment by yutongwangBIT** [comment]
it needs be generated by mapping, please run mapping at first
